### ISSUE TITLE
AnimatorCompatHelper Class Not Found Exception using AppCompat 27.0.0

### ISSUE THREAD

**Issue by Jaime97** [aritraroy/PinLockView#37]
When using compat library 27.0.0 the app crash when call animatorCompatHelper

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                       at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:515)
                                                       at android.support.v7.widget.DefaultItemAnimator.animateChange(DefaultItemAnimator.java:322)
                                                       at android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:149)
                                                       at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3836)
```

**Comment by hzshang** [comment]
@Jaime97 Add this at the end of build.gradle, it works for me
 ```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '24.1.0'
            }
        }
    }
}
```

**Comment by tatocaster** [comment]
any updates? @aritraroy

**Comment by mddanishansari** [comment]
Can someone please what exactly is this issue? And what is the permanent solution?

**Comment by Jaime97** [comment]
@mddanishansari  The issue was described in my first message, don't know if the solution given above should be consider as permanent really, that's why I didn't close the issue. Give me your opinion about it.
