### ISSUE TITLE
FATAL EXCEPTION

### ISSUE THREAD

**Issue by ShifuSD** [aritraroy/PinLockView#9]
How to fix?
`android.view.InflateException: Binary XML file line #9: Error inflating class android.widget.Button
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                          at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
                                                                          at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                                          at com.andrognito.pinlockview.PinLockAdapter.onCreateViewHolder(PinLockAdapter.java:41)`

Error here:
PinLockAdapter.class
`@Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        RecyclerView.ViewHolder viewHolder;
        if (viewType == VIEW_TYPE_NUMBER) {
            View view = View.inflate(parent.getContext(),R.layout.layout_number_item, null);
            viewHolder = new NumberViewHolder(view);
        } else {
            View view = View.inflate(parent.getContext(),R.layout.layout_delete_item, null);
            viewHolder = new DeleteViewHolder(view);
        }
        return viewHolder;
    }`

Error when:
...
//from service:
view_pin = View.inflate(this, R.layout.activity_lock_pin, null);
...
`    <com.andrognito.pinlockview.PinLockView
        android:id="@+id/pin_lock_view_Pin"
        android:layout_width="300dp"
        android:layout_height="wrap_content" />`

**Comment by aritraroy** [comment]
Which API level are you targeting here?

**Comment by ShifuSD** [comment]
not actual, thx!

**Comment by tapanrgohil** [comment]
I am getting same error can please help me ?
